name: Build binaries
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-latest, macos-13]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.5'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build binary
      run: pyinstaller --onefile src/peek.py
    
    - name: Rename binaries
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          mv dist/peek.exe dist/peek-windows-x86_64.exe
        elif [[ "${{ matrix.os }}" == "windows-11-arm" ]]; then
          mv dist/peek.exe dist/peek-windows-arm64.exe
        elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          mv dist/peek dist/peek-macos-arm64
        elif [[ "${{ matrix.os }}" == "macos-13" ]]; then
          mv dist/peek dist/peek-macos-x86_64
        elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          mv dist/peek dist/peek-linux-x86_64
        elif [[ "${{ matrix.os }}" == "ubuntu-24.04-arm" ]]; then
          mv dist/peek dist/peek-linux-arm64
        fi
      shell: bash
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binary-${{ matrix.os }}
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Create release
      uses: softprops/action-gh-release@v2.3.2
      
      with:
        files: |
          binary-ubuntu-latest/*
          binary-ubuntu-24.04-arm/*
          binary-windows-latest/*
          binary-windows-11-arm/*
          binary-macos-latest/*
          binary-macos-13/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
